# Change baseurl before deploy
baseurl = "https://qaisarnaqvi.github.io/"
languageCode = "en-us"

# This title appears in the browser tab and SEO results
title = "Prof. Dr. Qaisar Abbas Naqvi"

# Theme i18n support
defaultContentLanguage = "en"
hasCJKLanguage = false

# Comments are disabled in params.toml, so leave this blank
disqusShortname = ""

[pagination]
pagerSize = 5

